<?xml version="1.0" encoding="utf-8"?><Database Name="HisDemo" Class="MyDc2" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GLORYSCHOLARPC;Initial Catalog=HisDemo;User ID=sa" SettingsObjectName="MyDB.Properties.Settings" SettingsPropertyName="HisDemoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ROLE_USER" Member="ROLE_USER">
    <Type Name="ROLE_USER">
      <Column Name="Id" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
    </Type>
  </Table>
</Database>