#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBusinessLogic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HisDemo")]
	public partial class MyDc : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertINFRA_USER(INFRA_USER instance);
    partial void UpdateINFRA_USER(INFRA_USER instance);
    partial void DeleteINFRA_USER(INFRA_USER instance);
    #endregion
		
		public MyDc() : 
				base(global::TestBusinessLogic.Properties.Settings.Default.HisDemoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDc(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDc(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDc(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDc(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<INFRA_USER> INFRA_USER
		{
			get
			{
				return this.GetTable<INFRA_USER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INFRA_USER")]
	public partial class INFRA_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _NAME;
		
		private string _LOGIN_NAME;
		
		private string _PWD;
		
		private string _CODE;
		
		private string _DESCRIPTION;
		
		private string _INPUT_CODE2;
		
		private string _INPUT_CODE1;
		
		private string _INPUT_CODE3;
		
		private System.Nullable<System.DateTime> _CREATETIME;
		
		private System.Nullable<bool> _ISDELETE;
		
		private System.Nullable<int> _VERSION;
		
		private System.Nullable<int> _STATE;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnLOGIN_NAMEChanging(string value);
    partial void OnLOGIN_NAMEChanged();
    partial void OnPWDChanging(string value);
    partial void OnPWDChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnINPUT_CODE2Changing(string value);
    partial void OnINPUT_CODE2Changed();
    partial void OnINPUT_CODE1Changing(string value);
    partial void OnINPUT_CODE1Changed();
    partial void OnINPUT_CODE3Changing(string value);
    partial void OnINPUT_CODE3Changed();
    partial void OnCREATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATETIMEChanged();
    partial void OnISDELETEChanging(System.Nullable<bool> value);
    partial void OnISDELETEChanged();
    partial void OnVERSIONChanging(System.Nullable<int> value);
    partial void OnVERSIONChanged();
    partial void OnSTATEChanging(System.Nullable<int> value);
    partial void OnSTATEChanged();
    #endregion
		
		public INFRA_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGIN_NAME", DbType="NVarChar(255)")]
		public string LOGIN_NAME
		{
			get
			{
				return this._LOGIN_NAME;
			}
			set
			{
				if ((this._LOGIN_NAME != value))
				{
					this.OnLOGIN_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LOGIN_NAME = value;
					this.SendPropertyChanged("LOGIN_NAME");
					this.OnLOGIN_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PWD", DbType="NVarChar(255)")]
		public string PWD
		{
			get
			{
				return this._PWD;
			}
			set
			{
				if ((this._PWD != value))
				{
					this.OnPWDChanging(value);
					this.SendPropertyChanging();
					this._PWD = value;
					this.SendPropertyChanged("PWD");
					this.OnPWDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(255)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(255)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_CODE2", DbType="NVarChar(255)")]
		public string INPUT_CODE2
		{
			get
			{
				return this._INPUT_CODE2;
			}
			set
			{
				if ((this._INPUT_CODE2 != value))
				{
					this.OnINPUT_CODE2Changing(value);
					this.SendPropertyChanging();
					this._INPUT_CODE2 = value;
					this.SendPropertyChanged("INPUT_CODE2");
					this.OnINPUT_CODE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_CODE1", DbType="NVarChar(255)")]
		public string INPUT_CODE1
		{
			get
			{
				return this._INPUT_CODE1;
			}
			set
			{
				if ((this._INPUT_CODE1 != value))
				{
					this.OnINPUT_CODE1Changing(value);
					this.SendPropertyChanging();
					this._INPUT_CODE1 = value;
					this.SendPropertyChanged("INPUT_CODE1");
					this.OnINPUT_CODE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_CODE3", DbType="NVarChar(255)")]
		public string INPUT_CODE3
		{
			get
			{
				return this._INPUT_CODE3;
			}
			set
			{
				if ((this._INPUT_CODE3 != value))
				{
					this.OnINPUT_CODE3Changing(value);
					this.SendPropertyChanging();
					this._INPUT_CODE3 = value;
					this.SendPropertyChanged("INPUT_CODE3");
					this.OnINPUT_CODE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATETIME
		{
			get
			{
				return this._CREATETIME;
			}
			set
			{
				if ((this._CREATETIME != value))
				{
					this.OnCREATETIMEChanging(value);
					this.SendPropertyChanging();
					this._CREATETIME = value;
					this.SendPropertyChanged("CREATETIME");
					this.OnCREATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISDELETE", DbType="Bit")]
		public System.Nullable<bool> ISDELETE
		{
			get
			{
				return this._ISDELETE;
			}
			set
			{
				if ((this._ISDELETE != value))
				{
					this.OnISDELETEChanging(value);
					this.SendPropertyChanging();
					this._ISDELETE = value;
					this.SendPropertyChanged("ISDELETE");
					this.OnISDELETEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="Int")]
		public System.Nullable<int> VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this.OnVERSIONChanging(value);
					this.SendPropertyChanging();
					this._VERSION = value;
					this.SendPropertyChanged("VERSION");
					this.OnVERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="Int")]
		public System.Nullable<int> STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
